app_name: 'mechanize'
site_id: 'CGPHQ'
stats_url: 'http://localhost:9000/'

auth:
  username: chevron
  password: chevron123

uvicorn:
  app: 'main:app'
  host: '0.0.0.0'
  port: 8000
  log_level: info
  with_reload: true
  reload_delay: 0.25